<?php

namespace ContainerAEYnz7i;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NyQMJpoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NyQMJpo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NyQMJpo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cadastro' => ['privates', '.errored..service_locator.NyQMJpo.App\\Entity\\Cadastro', NULL, 'Cannot autowire service ".service_locator.NyQMJpo": it references class "App\\Entity\\Cadastro" but no such service exists.'],
        ], [
            'cadastro' => 'App\\Entity\\Cadastro',
        ]);
    }
}
