<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUru2qH8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUru2qH8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUru2qH8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUru2qH8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUru2qH8\App_KernelDevDebugContainer([
    'container.build_hash' => 'Uru2qH8',
    'container.build_id' => '100ac477',
    'container.build_time' => 1621188542,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUru2qH8');
