<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2tXurEt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2tXurEt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2tXurEt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2tXurEt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2tXurEt\App_KernelDevDebugContainer([
    'container.build_hash' => '2tXurEt',
    'container.build_id' => 'd2814b50',
    'container.build_time' => 1621300976,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2tXurEt');
