<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFfLkS3y\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFfLkS3y/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFfLkS3y.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFfLkS3y\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFfLkS3y\App_KernelDevDebugContainer([
    'container.build_hash' => 'FfLkS3y',
    'container.build_id' => '3f50a5ae',
    'container.build_time' => 1621471046,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFfLkS3y');
