<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\DefaultController::index'], [], [['text', '/']], [], []],
    'cadastro' => [[], ['_controller' => 'App\\Controller\\DefaultController::cadastro'], [], [['text', '/cadastro']], [], []],
    'consulta' => [[], ['_controller' => 'App\\Controller\\DefaultController::consulta'], [], [['text', '/consulta']], [], []],
    'quemsomos' => [[], ['_controller' => 'App\\Controller\\DefaultController::quemsomos'], [], [['text', '/quemsomos']], [], []],
    'sair' => [[], ['_controller' => 'App\\Controller\\DefaultController::sair'], [], [['text', '/sair']], [], []],
    'salvar' => [[], ['_controller' => 'App\\Controller\\DefaultController::salvar'], [], [['text', '/salvar']], [], []],
    'consultar' => [[], ['_controller' => 'App\\Controller\\DefaultController::consultar'], [], [['text', '/consultar']], [], []],
];
